apiVersion: v1
kind: Secret
metadata:
  name: race-secrets
  namespace: grupo4
type: Opaque
stringData:
  # Change these values before applying in production
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  RACE_API_TOKEN: "changeme-token"

