apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: default
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  NUM_PARTICIPANTS: "10"
  NUM_RACES: "3"
  PUBLISH_INTERVAL: "500"
  # Configuração para número variável de participantes
  VARIABLE_PARTICIPANTS: "true"
  MIN_PARTICIPANTS: "5"
  MAX_PARTICIPANTS: "15"
