apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: default
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  NUM_PARTICIPANTS: "10"
  NUM_RACES: "5"
  PUBLISH_INTERVAL: "1000"
