apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: grupo4
  labels:
    app: producer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3084
    targetPort: 3084
    protocol: TCP
  selector:
    app: producer
